- name: "Create the consul group"
  group:
    name: consul
    system: yes
  tags: ['consul']

- name: "Create the consul user"
  user:
    name: consul
    group: consul
    createhome: no
    system: yes
  tags: ['consul']

- name: "Check installed consul version"
  shell: "{{ consul_install_dir }}/consul version | head -1 | sed '1 s/Consul v//'"
  ignore_errors: True
  changed_when: False
  register: consul_installed_version
  tags: ['consul']

- name: "Get consul package checksum file"
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_SHA256SUMS"
    dest: "/tmp/consul_{{ consul_version }}_SHA256SUMS"
    owner: root
    group: root
    mode: 0644
  when: consul_installed_version|failed or consul_installed_version.stdout != consul_version
  tags: ['consul']

- name: "Get consul checksum"
  shell: "grep consul_{{ consul_version }}_{{ consul_platform }}.zip /tmp/consul_{{ consul_version }}_SHA256SUMS"
  register: consul_sha256
  changed_when: false
  when: consul_installed_version|failed or consul_installed_version.stdout != consul_version
  tags: ['consul']

- name: "Download consul"
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ consul_platform }}.zip"
    dest: "/tmp/consul_{{ consul_version }}_{{ consul_platform }}.zip"
    sha256sum: "{{ consul_sha256.stdout.split(' ')|first }}"
    owner: root
    group: root
    mode: 0644
  register: consul_download
  when: consul_installed_version|failed or consul_installed_version.stdout != consul_version
  tags: ['consul']

- name: "Make sure that unzip is installed"
  package: name=unzip state=present
  tags: ['consul']

- name: "Unzip consul archive"
  unarchive:
    src: "{{ consul_download.dest }}"
    dest: "{{ consul_install_dir }}"
    copy: no
    owner: root
    group: root
    mode: 0755
  when: consul_installed_version|failed or consul_installed_version.stdout != consul_version
  notify: Restart consul
  tags: ['consul']

- name: "Create consul directories"
  file:
    path: "{{ item }}"
    owner: consul
    group: consul
    mode: 0755
    state: directory
  with_items:
    - /etc/consul
    - /var/lib/consul
  tags: ['consul']

- name: "Configure consul"
  template:
    dest: /etc/consul/config.json
    src: "{{ consul_template }}"
    owner: consul
    group: consul
    mode: 0644
  notify: Restart consul
  tags: ['consul', 'files']

- name: "Install the systemd unit file"
  copy:
    dest: /etc/systemd/system/consul.service
    src: consul.systemd
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd
  tags: ['consul', 'files']

- name: "Ensure consul is started and enabled on boot"
  service:
    name: consul
    state: started
    enabled: yes
  tags: ['consul']
